### ISSUE TITLE
Telegram ZHunger Chatbot Is not working

### ISSUE THREAD

**Issue by sahajoydeep** [BikashKumarSethy/RoyalHackElites#1]
Telegram ZHunger Chatbot Is not working.

The send message is not working when you click on the tab of send message the site doesn't respond.

**Comment by BikashKumarSethy** [comment]
Hi sahajoydeep2002 , I checked recently it's now working in Telegram as well as Web(best supported in Chrome). As It's a mobile Application we request you to please open the link through mobile , it will directly take you to our ZHunger Application on Telegram where it would be more comfortable chatting, You can try with the messages like I am Hungry, Thank You, You can give ratings for our improvement and also If you have food type "I have food". Let me know if you still face any issues, I am available (Ph No: 9040614161). Thanks, Bikash Sethy

**Comment by BikashKumarSethy** [comment]
Hi sahajoydeep2002 , I checked recently it's now working in Telegram as well as Web(best supported in Chrome). As It's a mobile Application, directly clicking on the link will not work on web, therefore we request you to please open the link through mobile , it will directly take you to our ZHunger Application on Telegram where it would be more comfortable chatting, You can try with the messages like I am Hungry, Thank You, You can give ratings for our improvement and also If you have food type "I have food". Let me know if you still face any issues please help us providing the error screenshot, I am available (Ph No: 9040614161). Thanks, Bikash Sethy
